## ===========================================================================
## CHRONO WORKBENCH:github.com/Concrete-Chrono-Development/chrono-preprocessor
##
## Copyright (c) 2023 
## All rights reserved. 
##
## Use of this source code is governed by a BSD-style license that can be
## found in the LICENSE file at the top level of the distribution and at
## github.com/Concrete-Chrono-Development/chrono-preprocessor/blob/main/LICENSE
##
## ===========================================================================
## Developed by Northwestern University
## Primary Authors: Matthew Troemner
## ===========================================================================
##
##
##
## ===========================================================================

# pyright: reportMissingImports=false
from pathlib import Path
import FreeCAD as App
from femtools import membertools
import numpy as np

def mkAbaqusInput(elementType, analysisName, materialProps, materialPropsDesc, materialPropsVals, simProps, simPropsValues, \
    nodesFilename, elemFilename, facetsFilename, geoName, outDir, outName):

    """
    Variables:
    --------------------------------------------------------------------------
    ### Inputs ###
    - elementType:      The type of element that will be used
    - analysisName:     The name of the analysis
    - materialProps:    The names of the material properties
    - materialPropsVals:The values of the material properties
    - simProps:         The names of the simulation properties
    - simPropsValues:   The values of the simulation properties
    - nodesFilename:    The name of the file containing the nodes
    - elemFilename:     The name of the file containing the tets
    - facetsFilename:   The name of the file containing the facets
    - geoName:          The name of the geometry
    - outDir:           The output directory
    - outName:          The output name
    --------------------------------------------------------------------------
    ### Outputs ###
    - An input file for Abaqus
    --------------------------------------------------------------------------
    """


    doc = App.ActiveDocument

    if elementType == 'LDPM':
        analysis = doc.getObject("LDPManalysis")

    # Read in the nodes from the nodes file and store in a numpy array
    with open(Path(outDir + outName + '/' + nodesFilename)) as f:
        nodes = f.readlines()
    allNodes = np.array([x.strip().split() for x in nodes[1:]], dtype=np.float64)

    # Read in the tets from the tets file and store in a numpy array
    with open(Path(outDir + outName + '/' + elemFilename)) as f:
        tets = f.readlines()
    allTets = np.array([x.strip().split() for x in tets[1:]], dtype=np.int64)




    with open(Path(outDir + outName + '/' + geoName + '-mesh.inp'),"w") as f:

        f.write('*Heading\n')
        f.write('** Job name: ' + geoName + ' Model name: Model-' + geoName + '\n')
        f.write('** Generated by: Abaqus/CAE 2019\n')
        f.write('**\n')
        f.write('** PARTS\n')
        f.write('**\n')
        f.write('*Part, name=' + geoName + '\n')
        f.write('*Node\n')
        for x in range(0,len(allNodes)):
                f.write(str(x+1) + ', ' + str(allNodes[x,0]) + ', ' \
                    + str(allNodes[x,1]) + ', '  + str(allNodes[x,2]) \
                    + '\n')
        f.write('*Element, type=C3D4\n')
        for x in range(0,len(allTets)):
                f.write(str(x+1) + ', ' + str(allTets[x,0].astype(int)) \
                    + ', ' \
                    + str(allTets[x,1].astype(int)) + ', '  \
                    + str(allTets[x,2].astype(int)) \
                    + ', '  + str(allTets[x,3].astype(int)) +'\n')
        f.write('*End Part\n')
        f.write('**\n')
        f.write('**\n')
        f.write('** ASSEMBLY\n')
        f.write('**\n')
        f.write('*Assembly, name=Assembly\n')
        f.write('**\n')
        f.write('*Instance, name=' + geoName + '-1, part=' + geoName + '\n')
        f.write('*End Instance\n')
        f.write('**\n')
        f.write('*End Assembly\n')
